"""add fundamental facts and portfolio ledger"""
import sqlalchemy as sa

from alembic import op

revision = '23252154b600'
down_revision = 'b9ac2b3051e7'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('quote', sa.String(length=3), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rate', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'base', 'quote', 'date')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_user_id'), ['user_id'], unique=False)

    op.create_table('fundamental_facts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('concept', sa.String(length=128), nullable=False),
    sa.Column('taxonomy', sa.String(length=32), nullable=False),
    sa.Column('source_concept', sa.String(length=256), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=80), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('filed', sa.Date(), nullable=False),
    sa.Column('accession', sa.String(length=32), nullable=False),
    sa.Column('fiscal_period', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fundamental_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fundamental_facts_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamental_facts_concept'), ['concept'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamental_facts_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_fundamental_facts_filed'), ['filed'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('transaction_type', sa.String(length=24), nullable=False),
    sa.Column('quantity', sa.String(length=80), nullable=False),
    sa.Column('price', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fees', sa.String(length=80), nullable=False),
    sa.Column('taxes', sa.String(length=80), nullable=False),
    sa.Column('fx_rate', sa.String(length=80), nullable=False),
    sa.Column('broker', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'external_id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_asset_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('fundamental_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fundamental_facts_filed'))
        batch_op.drop_index(batch_op.f('ix_fundamental_facts_end'))
        batch_op.drop_index(batch_op.f('ix_fundamental_facts_concept'))
        batch_op.drop_index(batch_op.f('ix_fundamental_facts_asset_id'))

    op.drop_table('fundamental_facts')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_user_id'))

    op.drop_table('portfolios')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###

