"""record verified share bases"""
import sqlalchemy as sa

from alembic import op

revision = '52ff5305a742'
down_revision = '23252154b600'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_prices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valuation_basis', sa.String(length=64), nullable=True))

    with op.batch_alter_table('fundamental_facts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valuation_basis', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundamental_facts', schema=None) as batch_op:
        batch_op.drop_column('valuation_basis')

    with op.batch_alter_table('asset_prices', schema=None) as batch_op:
        batch_op.drop_column('valuation_basis')

    # ### end Alembic commands ###
