"""add assets providers cache and watchlists"""

import sqlalchemy as sa

from alembic import op

revision = "b9ac2b3051e7"
down_revision = "d2854c934c42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_cache",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("api_cache", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_cache_provider"), ["provider"], unique=False)

    op.create_table(
        "provider_usage",
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("month", sa.String(length=7), nullable=False),
        sa.Column("daily_count", sa.Integer(), nullable=False),
        sa.Column("monthly_count", sa.Integer(), nullable=False),
        sa.Column("minute_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("minute_count", sa.Integer(), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.Column("last_request", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_after", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("provider"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("asset_type", sa.String(length=24), nullable=False),
        sa.Column("exchange", sa.String(length=64), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("sector", sa.String(length=128), nullable=True),
        sa.Column("industry", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("cik", sa.String(length=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "symbol", "exchange", "asset_type"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assets_user_id"), ["user_id"], unique=False)

    op.create_table(
        "watchlists",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("watchlists", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_watchlists_user_id"), ["user_id"], unique=False)

    op.create_table(
        "asset_prices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("open", sa.String(length=80), nullable=True),
        sa.Column("high", sa.String(length=80), nullable=True),
        sa.Column("low", sa.String(length=80), nullable=True),
        sa.Column("close", sa.String(length=80), nullable=False),
        sa.Column("volume", sa.String(length=80), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("adjustment", sa.String(length=24), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_id", "date", "provider"),
    )
    with op.batch_alter_table("asset_prices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_asset_prices_asset_id"), ["asset_id"], unique=False)

    op.create_table(
        "provider_mappings",
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_symbol", sa.String(length=128), nullable=False),
        sa.Column("provider_asset_id", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("asset_id", "provider"),
    )
    op.create_table(
        "watchlist_assets",
        sa.Column("watchlist_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("tags", sa.String(length=500), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
        ),
        sa.ForeignKeyConstraint(["watchlist_id"], ["watchlists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("watchlist_id", "asset_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("watchlist_assets")
    op.drop_table("provider_mappings")
    with op.batch_alter_table("asset_prices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_asset_prices_asset_id"))

    op.drop_table("asset_prices")
    with op.batch_alter_table("watchlists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_watchlists_user_id"))

    op.drop_table("watchlists")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_user_id"))

    op.drop_table("assets")
    op.drop_table("provider_usage")
    with op.batch_alter_table("api_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_cache_provider"))

    op.drop_table("api_cache")
    # ### end Alembic commands ###
